workspace:
  base: /go
  path: src/github.com/jhernandezb/go-multasgt

pipeline:
  test:
    image: golang:1.9
    commands:
      - go test -cover github.com/jhernandezb/go-multasgt/entities/emixtra
